### ISSUE TITLE
Copy/pasted custom block components may not be preserved

### ISSUE THREAD

**Issue by hellendag** [facebook/draft-js#125]
When copying a custom block within a `Draft` editor, pasting it back into the editor may not preserve it.

This can be reproduced within FB Notes by copying a section of text that includes an embedded photo, then pasting it back into the editor.

Source of issue: we check the DOM clipboard plaintext with the internal clipboard text to determine whether the pasted contents are the same as the internal clipboard. Since the custom block may render something other than the plain text of the `ContentBlock`, the check may fail, in which case the HTML contents are parsed and pasted instead. (https://github.com/facebook/draft-js/blob/master/src/component/handlers/edit/editOnPaste.js#L113)

My idea to resolve this is to have an Editor-level random key to be rendered as an attribute within the DOM, perhaps at the `DraftEditorBlock` level. During a paste, we can check the pasted HTML for the random key. If it is present, we can assume that the paste is internal and should use the internal clipboard. If it is absent, we use the raw HTML instead.

This should preserve custom blocks during the paste, since the internal clipboard representation is just an `OrderedMap<string, ContentBlock>` being inserted into the `ContentState`. Following the paste, the custom block will be rendered correctly in the Editor.

**Comment by spicyj** [comment]
Does it make more sense to generate a per-copy key rather than a per-editor one? Not sure how much control we have there.

**Comment by hellendag** [comment]
It would have to be part of the copied HTML in order to have something to read from at paste time. So I think a per-copy key would mean having something rendered into the editor DOM prior to the copy command, then changed afterward. Not sure if that's necessary, if the per-editor key is effective enough.

**Comment by remko** [comment]
Is this just for *custom* block components? Copy/pasting H1 doesn't preserve the H1 either for me.

**Comment by hellendag** [comment]
@remko In the case you describe, it may be that the type of the target block for the paste is overriding the pasted input. The bug here is different, but there may be some worthwhile discussion around default block paste behavior.

**Comment by hellendag** [comment]
The issue in question here is resolved by https://github.com/facebook/draft-js/commit/c0f241482b393d31937409e0104d1d67b8cc7952.

**Comment by ivan-moroz** [comment]
I have a problem using draft.js on my web application. I need to change pasted from MS Word text. Using the **handlePastedText** method I try to change the pasted HTML and create new editorState:

`var fragment = convertFromHTML(this._clearHTML(html));

            var newContentState = Modifier.replaceWithFragment(
                contentState,
                selectionState,
                fragment
            );`

but **fragment** is a simple array. Draft js needs the OrderedMap, so what I'm doing wrong.
Thank you so much

**Comment by ivan-moroz** [comment]
The previous issue solved. Maybe will be usfull.

```
var fragment = convertFromHTML(this._clearHTML(html))            
var newContentState = Modifier.replaceWithFragment(
                contentState,
                selectionState,
                BlockMapBuilder.createFromArray(fragment)
            );
```

**Comment by basicallydan** [comment]
aha
....

**Comment by IzaGz** [comment]
@hellendag Dear, i still cant get it. Pastign from ms word  gives me wrong line breaks , wrong format. Using 0.10.1 . What is wrong? how to resolve? Help please

**Comment by IzaGz** [comment]
@ivan-moroz how do use the `handlePastedText`, what you returned inside? Dear, please need help. I am pasting from ms word and get wrong new lines formats, new lines are lost.

**Comment by ivan-moroz** [comment]
IzaGz it's simply prop to editor:

`
Editor = require('draft-js').Editor,

....
    _handlePastedText: function (text, html) {
        if (html) {
            this._pastHTMLValue(html);
            return true;
        }
    },

render: (
  <Editor
     handlePastedText={this._handlePastedText}
  />
)

`

**Comment by ivan-moroz** [comment]
_pastHTMLValue: function(htmlString){
        var editorState = this.state.editorState;
        var contentState = editorState.getCurrentContent();
        var currentStyle = editorState.getCurrentInlineStyle();
        var selectionState = editorState.getSelection();
        var cleared = richTextUtil.clearHTML(htmlString);
        var fragment = convertFromHTML(cleared);
        var newContentState = Modifier.replaceWithFragment(
            contentState,
            selectionState,
            BlockMapBuilder.createFromArray(fragment)
        );
        editorState = EditorState.push(
            editorState,
            newContentState
        );
        this._onChange(editorState);
    },

**Comment by ivan-moroz** [comment]
clearHTML: function (stringHTML) {
        var cleared = stringHTML
            .replace(/<html[\s\S]*?>/gmi, '')
            .replace(/<\/html>[\s\S]*/gmi, '')
            .replace(/<head>[\s\S]*?<\/head>/gmi, '')
            .replace(/<p class=MsoListParagraphCxSp[\s\S]*?mso-list[\s\S]*?<!\[endif\]>([\s\S]*?)<o:p><\/o:p>(<\/span>)?(<\/i>)?(<\/b>)?<\/p>/gmi, '[LI]$1[/LI]')
            .replace(/<\/p>[\s]*<p.*?>/gmi, '<br>')
            .replace(/<br.*?>/gmi, '[BR]')
            .replace(/<\/ul>/gmi, '[/UL]')
            .replace(/<ul.*?>/gmi, '[UL]')
            .replace(/<\/li>/gmi, '[/LI]')
            .replace(/<li.*?>/gmi, '[LI]')
            .replace(/<a(.*?)>([\s\S]*?)<\/a>/gmi, '[A$1]$2[/A]')
            .replace(/<[\s\S]*?>/gmi, '')
            .replace(/\[A(.*?)\]([\s\S]*?)\[\/A\]/gmi, '<a$1>$2</a>')
            .replace(/\[UL\]/gm, '<ul>')
            .replace(/\[LI\]/gm, '<li>')
            .replace(/\[\/UL\]/gm, '</ul>')
            .replace(/\[\/LI\]/gm, '</li>')
            .replace(/\[BR\]/gmi, '<br />');

        var root = document.createElement('root');
        root.innerHTML = cleared;
        var list = root.getElementsByTagName('LI');
        var ul;
        for (var i = 0; i < list.length; i++) {
            var li = list[i];
            var parent = li.parentNode;
            if (parent.tagName !== 'UL') {
                var prev = li.previousSibling;
                var prevElement = li.previousElementSibling;
                if (prev && prev.nodeType === 3 && !!prev.textContent.trim() || !prevElement || prevElement.tagName !== 'UL') {
                    ul = document.createElement('UL');
                    parent.insertBefore(ul, li);
                }
                ul.appendChild(li);
            }
        }
        return root.innerHTML;
    },

**Comment by ivan-moroz** [comment]
clearHTML - for MS Word, keep ul and ol transfrom to ul

**Comment by ivan-moroz** [comment]
`clearHTML: function (stringHTML) {
        var cleared = stringHTML
            .replace(/<html[\s\S]*?>/gmi, '')
            .replace(/<\/html>[\s\S]*/gmi, '')
            .replace(/<head>[\s\S]*?<\/head>/gmi, '')
            .replace(/<p class=MsoListParagraphCxSp[\s\S]*?mso-list[\s\S]*?<!\[endif\]>([\s\S]*?)<o:p><\/o:p>(<\/span>)?(<\/i>)?(<\/b>)?<\/p>/gmi, '[LI]$1[/LI]')
            .replace(/<\/p>[\s]*<p.*?>/gmi, '<br>')
            .replace(/<br.*?>/gmi, '[BR]')
            .replace(/<\/ul>/gmi, '[/UL]')
            .replace(/<ul.*?>/gmi, '[UL]')
            .replace(/<\/li>/gmi, '[/LI]')
            .replace(/<li.*?>/gmi, '[LI]')
            .replace(/<a(.*?)>([\s\S]*?)<\/a>/gmi, '[A$1]$2[/A]')
            .replace(/<[\s\S]*?>/gmi, '')
            .replace(/\[A(.*?)\]([\s\S]*?)\[\/A\]/gmi, '<a$1>$2</a>')
            .replace(/\[UL\]/gm, '<ul>')
            .replace(/\[LI\]/gm, '<li>')
            .replace(/\[\/UL\]/gm, '</ul>')
            .replace(/\[\/LI\]/gm, '</li>')
            .replace(/\[BR\]/gmi, '<br />');

        var root = document.createElement('root');
        root.innerHTML = cleared;
        var list = root.getElementsByTagName('LI');
        var ul;
        for (var i = 0; i < list.length; i++) {
            var li = list[i];
            var parent = li.parentNode;
            if (parent.tagName !== 'UL') {
                var prev = li.previousSibling;
                var prevElement = li.previousElementSibling;
                if (prev && prev.nodeType === 3 && !!prev.textContent.trim() || !prevElement || prevElement.tagName !== 'UL') {
                    ul = document.createElement('UL');
                    parent.insertBefore(ul, li);
                }
                ul.appendChild(li);
            }
        }
        return root.innerHTML;
    },`
